### ISSUE TITLE
Release 0.99 to PyPi

### ISSUE THREAD

**Issue by aivarannamaa** [robertlugg/easygui#113]
Currently `pip install easygui` gives version unusable with Python 3. 

Seems that the fixes are already commited. Please release current state to PyPi. Even if it has some bugs left, it's still better than 0.98.

**Comment by gbaman** [comment]
Agreed, would be great to get it released, especially with [this bug](https://github.com/robertlugg/easygui/issues/97) in the current public version.
cc @zadacka

**Comment by zadacka** [comment]
@robertlugg - do you want to make an official v0.99 tag, and I'll update the version on PyPi?

**Comment by robertlugg** [comment]
Hi @zadacka, are you happy with the code quality?  I have no reason to suspect a problem but I haven't tested it.  If you are OK, I can just tag it.  Otherwise I need to dedicate some time this weekend to build my confidence in it.

**Comment by zadacka** [comment]
@robertlugg (and for visibility to the others) we'll wait until the planned changes are made before making the v0.99 tag and releasing to PyPi. I'm almost done with moving house now, and can turn this around quickly when needed!

**Comment by jjdenis** [comment]
I have advanced quite a lot in develop. New demos for buttonbox, new tests, better support for callbacks, big refactoring, hotkeys in lowercase, message is centered, choices can be expressed in many new ways... Tested in linux, 2.7 and 3.5.

I would like you try it, and if possible run botton_box_demos.py and test_buton_box.py on other platforms.

But I would't wait to push current master to PyPi, maybe under v0.98.1 tag

**Comment by thomas-haslwanter** [comment]
Please release a 0.98.1 update - the incompatability with Python 3 is REALLY a show-stopper!
Thanks, Thomas

**Comment by dmcnich** [comment]
Six months seems like a long time to leave a broken module up on PyPi

**Comment by jjdenis** [comment]
I have made the release (I hope I did it right, it is my fist time): @zadacka Can you update to Pypi?

**Comment by zadacka** [comment]
Will do! Should be able to update this tomorrow evening (UK time). Thanks @Juan

Sorry for the brevity - Sent from Mobile
On Thu, Jan 5, 2017 at 5:31 PM, Juan José Denis Corrales <notifications@github.com> wrote:
I have made the release (I hope I did it right, it is my fist time): @zadacka [https://github.com/zadacka] Can you update to Pypi?

**Comment by dirkpetersen** [comment]
I just tried pip3 install --upgrade pip ..no luck, the package is still from june

**Comment by zadacka** [comment]
Updated on PyPi now. Tested locally with a `pip install pypi --upgrade` and I get v0.98.1

Is everyone else okay with this?

**Comment by antorix** [comment]
Hi. After upgrading to Python 3.6.0 and re-installing Easygui just now from PyPi, I always get this error on any widgets:

File "C:\Users\antor\AppData\Local\Programs\Python\Python36\lib\gettext.py", line 206, in _expand_lang
    loc = locale.normalize(loc)
AttributeError: module 'locale' has no attribute 'normalize'

**Comment by jjdenis** [comment]
I don't seem to be able to make it work in 2.7.12.

>>> import easygui
>>> easygui.egdemo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'egdemo'
>>>

**Comment by dirkpetersen** [comment]
0.98.1 easygui.egdemo() works fine for me in 2.7.8 and 3.6.0

**Comment by zadacka** [comment]
Okay, not so good on the upgrade then.
I'll revert the version on PyPi when back at the computer and then work on fixing it for Python 2.x and Python 3.x. Thanks very much for the feedback, all, and apologies for the abortive release.

Sorry for the brevity - Sent from Mobile
On Fri, Jan 6, 2017 at 10:00 PM, Juan José Denis Corrales <notifications@github.com> wrote:
I don't seem to be able to make it work in 2.7.12.

import easygui
easygui.egdemo()
Traceback (most recent call last):
File "", line 1, in
AttributeError: 'module' object has no attribute 'egdemo'

**Comment by dirkpetersen** [comment]
actually would please not remove 0.98.1. It works fine for me (that is on Linux)

**Comment by zadacka** [comment]
Huh, strange.
Juan, Anton - change of plans. I'll try to reproduce your problems before reverting. Dirk - thanks for checking.
Sorry for the brevity - Sent from Mobile
On Fri, Jan 6, 2017 at 10:11 PM, alexander.zawadzki@gmail.com <alexander.zawadzki@gmail.com> wrote:
Okay, not so good on the upgrade then.
I'll revert the version on PyPi when back at the computer and then work on fixing it for Python 2.x and Python 3.x. Thanks very much for the feedback, all, and apologies for the abortive release.

Sorry for the brevity - Sent from Mobile
On Fri, Jan 6, 2017 at 10:00 PM, Juan José Denis Corrales <notifications@github.com> wrote:
I don't seem to be able to make it work in 2.7.12.

import easygui
easygui.egdemo()
Traceback (most recent call last):
File "", line 1, in
AttributeError: 'module' object has no attribute 'egdemo'

**Comment by antorix** [comment]
Ok, I completely reinstalled Python 3.6.0, and this error is now gone. My version is 0.98.1 now, and everything works fine.

**Comment by jjdenis** [comment]
I uninstalled and installed easygui and... everything looks fine!

**Comment by jjdenis** [comment]
Also don't forget to check out my enhancements, in develop.

**Comment by spyoungtech** [comment]
pip install works fine on mac os x (sierra) and windows 7; Python 3.6

Cheers.
